name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: running unit tests
        run: go test ./... -cover
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: test-z
        run: test -z $(go fmt ./...)
      - name: go fmt
        run: go fmt ./...
      - name: install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: staticcheck
        run: staticcheck ./...
  